import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Suspense } from 'react'


function ListLoading() {
  return (
    <div className=' grid items-center h-[64px] '>
      
<div role="status" className="w-full animate-pulse">
    <div className="h-2.5 w-full bg-gray-200 rounded-full dark:bg-gray-700"></div>
    <span className="sr-only">Loading...</span>
      </div>

      <div className="flex items-center justify-between">
      <div role="status" className="w-full animate-pulse">
    <div className="h-2.5 w-12 bg-gray-200 rounded-full dark:bg-gray-700"></div>
    <span className="sr-only">Loading...</span>
      </div>
      <div role="status" className="w-full animate-pulse">
    <div className="h-2.5 w-full bg-gray-200 rounded-full dark:bg-gray-700"></div>
    <span className="sr-only">Loading...</span>
      </div>

      </div>
    </div>
  )
}

export const metadata: Metadata = {
  title: 'Challenge',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   
  async function ListItem({id}: {id: number}) {
    const post = await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`).then((resp) => resp.
    json() as Promise<{title: string; url: string; by: string}>)
    
    return <div className=' flex flex-col gap-2 h-[64px] '>
        <p className='truncate'>
        {post.title} || {post.by}
        </p> 
        <div className='flex items-center justify-between opacity-50'>
          <p> {post.by} </p>
          <p className='bg-white rounded-full px-2 text-black'>Visit website {`>`} </p>
        </div>
    </div>
  }


  const posts = await fetch(`https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty&limitToFirst=10&orderBy="$key"`).then(resp => resp.json() as Promise<number[]>);
  return (
    <html lang="en">
      <body className='grid grid-rows-[60px,1fr] '>
        <header className='grid place-content-center bg-yellow-400 font-semibold text-black'>
         Hackernews Reader
        </header>
        <main className='grid grid-cols-[320px,1fr] gap-4'>
        <aside>
          <ul className='p-4 flex flex-col gap-4'>
            {posts.map((id) => (
              <li key={id}>
              <Link  href={`/${id}`}>
                <Suspense fallback={<ListLoading/>}>
                  <ListItem id={id}/>
               </Suspense>
               </Link>
               </li>
              ))}
          </ul>
       
        </aside>
        <section>
          {children}
        </section>
        </main>
        </body>
    </html>
  )
}
